### ISSUE TITLE
Mesh Smoothing support

### ISSUE THREAD

**Issue by lgleim** [Zielon/ParallelQSlim#3]
The [Readme suggest](https://github.com/Zielon/ParallelQSlim/blob/master/README.md?plain=1#L42), that the code implements mesh smoothing. Nevertheless, the current implementation just tries to [read a different mesh](https://github.com/Zielon/ParallelQSlim/blob/master/src/main.cpp#L155) with the `_smoothed` suffix and throws an error if that does not exist. Is this intentional?

**Comment by Zielon** [comment]
Hello,  I left out this part of the code because of OpenMesh dependency. If you are interested in the original code with smoothing you can find it under [simplify_mesh/src/smooth/taubin.hpp](https://github.com/Zielon/ParallelQSlim/commit/4a255219c8aace2e4e06a04c96a90400a4981f49).
