### ISSUE TITLE
Segmentation Fault when parsing a .ply with property list uchar uint vertex_indices

### ISSUE THREAD

**Issue by ManosAgelidis** [Zielon/ParallelQSlim#4]
Hi, great repo! I was trying to simplify a .ply mesh which is causing a seg fault when executing the script. It seems to crash when it's executing this loop 

![image](https://user-images.githubusercontent.com/17083612/215487976-5d770d18-3d29-4c74-853c-91e921120d31.png)

I checked an example ply that I found online (https://www.artec3d.com/3d-models/bearded-guy-hd) vs my .ply and and I noticed that my .ply header is slightly different, in particular the header that doesn't work is like this (notice the uint in line 18) 

![image](https://user-images.githubusercontent.com/17083612/215488473-c19968e3-462a-47da-ba56-52743ca87a9c.png)

vs the header that works 

![image](https://user-images.githubusercontent.com/17083612/215488695-07b38d39-bdf2-4fa0-8755-99da1cff5572.png)

Any ideas as to where the problem might be coming from? thanks!

**Comment by stedf** [comment]
@ManosAgelidis in Blender you need to export to PLY without exporting `Normals`, `UVs` and `vertex colors` and make sure that `Format ASCII` is not selected either.
